frontend/frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import (handler404, handler500)

from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('super/', include('super.urls'), name='super'),

    path('user/',include('user.urls'), name='user'),
    path('category/<pk>/',CategoryView.as_view(), name='category'),
    path('product/',include('product.urls'), name='product'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 ='frontend.views.page_not_found'
handler500 ='frontend.views.server_error'

frontend/product/urls.py
from django.urls import path

from .views import ProductDV, OrderView, OrderDV

app_name='product'

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order/<pk>', OrderDV.as_view(), name='order_detail'),
    path('<pk>/',ProductDV.as_view(), name='detail'),
]

frontend/super/urls.py
from django.urls import path

from super.order_views import OrderLV, OrderDV
from .category_views import *
from .views import *
from .product_views import *

app_name='super'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('members/', MemberLV.as_view(), name='member-list'),

    path('products/', ProductLV.as_view(), name='product-list'),
    path('products/add/', ProductCV.as_view(), name='product-add'),
    path('products/update/<pk>', ProductUV.as_view(), name='product-update'),
    path('products/delete/<pk>', ProductDV.as_view(), name='product-delete'),

    path('category/', CategoryLV.as_view(), name='category-list'),
    path('category/add/', CategoryCV.as_view(), name='category-add'),
    path('category/delete/', ProductDV.as_view(), name='category-delete'),

    path('order/', OrderLV.as_view(), name='order-list'),
    path('order/<pk>', OrderDV.as_view(), name='order-detail'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

frontend/user/urls.py
from django.urls import path

from .views import *

app_name='user'

urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('join/', JoinView.as_view(), name='join'),
    path('checkid/<check_id>/', check_id, name='check_id'),
    path('cart/', CartView.as_view(), name='cart'),
    path('order/', OrderView.as_view(), name='order'),
]

frontend/product/forms.py
from django import forms


class OrderForm(forms.Form):
    user = forms.IntegerField(label="주문자")
    sender_name = forms.CharField(label="주문자 명", max_length=100)
    sender_email = forms.EmailField(label='주문자 이메일')
    sender_phone_number = forms.CharField(label='주문자 전화번호', max_length=50)

    receiver_name = forms.CharField(label='받는사람')
    receiver_phone_number = forms.CharField(label='받는사람 전화번호', max_length=50)
    receiver_address = forms.CharField(label='받는사람 주소', max_length=250)
    delivery_message = forms.CharField(label="배송 메시지")

    pay_type = forms.ChoiceField(label='결제방법', choices=[('0', '무통장입금'),
                                                        ('1', '휴대폰소액결제'),
                                                        ('2', '실시간계좌이체'),
                                                        ('3', '신용카드결제'),
                                                        ('4', '카카오페이')])

frontend/super/views.py
import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, View

from frontend import default

root_url= default.root_url
api_url = default.api_url
header = default.headers

class MemberLV(TemplateView):
    template_name = 'super/member-list.html'

    def get_context_data(self, **kwargs):
        response = requests.get(root_url + api_url + "super/users/")
        data = dict()
        if response.status_code is not 200:
            data['members'] = []
            return data

        data['members']=response.json()['data']
        return data



class LoginView(View):
    def get(self, request):
        return render(request,'super/login.html')

    def post(self, request):
        super = {
            'user_id':request.POST['user_id'],
            'password':request.POST['password']
        }
        response = requests.post(root_url+api_url+'super/login/', headers=header, data=super)
        if response.status_code is not 200 :
            return HttpResponseRedirect(reverse("super:login"))

        request.session['superuser'] = response.json()['data']

        return render(request, 'super/home.html')


class Logout(View):
    def get(self, request):
        del request.session['superuser']
        return HttpResponseRedirect(reverse('super:login'))


class Home(View):
    def get(self, request):
        if 'superuser' in request.session:
            return render(request,'super/home.html')
        return HttpResponseRedirect(reverse("super:login"))

frontend/templates/super/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/super/sidebar.css' %}">
    <link rel="stylesheet" type="text/css" href='{% block extrastyle %}{% endblock %}'/>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Patua+One&display=swap" rel="stylesheet">
    <script src='{% block extrascript %}{% endblock %}'></script>
    {% block extrafile %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'super:home' %}">홈</a></li>
                    <li><a href="{% url 'super:category-list' %}">카테고리 조회</a></li>
                    <li><a href="{% url 'super:category-add' %}">카테고리 등록</a></li>
                    <li><a href="{% url 'super:product-list' %}">상품 조회</a></li>
                    <li><a href="{% url 'super:product-add' %}">상품 등록</a></li>
                    <li><a href="{% url 'super:member-list' %}">회원 조회</a></li>
                    <li><a href="{% url 'super:order-list' %}">주문 조회</a></li>
                    <li><a href="">장바구니 목록</a></li>
                    <li><a href="{% url 'home' %}">쇼핑몰로 가기</a></li>
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

frontend/templates/super/category-list.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/table.css" %}
{% endblock %}

{% block content %}
<div id="content">
    <br/>
    <div class="titleArea">
        <h2>category list</h2>
    </div>
    <br/>
    <table class="table">
        <tr>
            <th>이름</th>
            <th>상위 카테고리</th>
            <th>우선순위</th>
            <th></th>
        </tr>
        {% load custom_tags %}
        {% for category in categorys|sort_by:'priority' %}
        <tr>
            <td>{{ category.name }}</td>
            {% if category.parent is None %}
            <td></td>
            {% else %}
            <td>{{ category.parent.name }}</td>
            {% endif %}
            <td>{{ category.priority }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

frontend/templates/super/categroy-add.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/product-add.css" %}
{% endblock %}
{% block extrafile %}
<script type="text/javascript" src="{% static 'script/jquery.min.js' %}"></script>
{% endblock %}

{% block content %}
<div id="content">
    <br/>
    <div class="titleArea">
        <h2>category add</h2>
    </div>
    <br/>
<div class="box">
    <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
        <input id="csrf_token" type="hidden" value="{{ csrf_token }}"/>
        <div class="product-add">
            <fieldset>
                <div class="form-inline form-group">
                    <label class="label col-sm-2">
                        카테고리 명
                    </label>
                    <div class="col-sm-10">
                        {% if category is None %}
                        <input name="name" class="form-control" type="text">
                        {% else %}
                        <input name="name" class="form-control" type="text" value="{{ category.name }}">
                        {% endif %}
                    </div>
                </div>

                <div class="form-inline form-group">
                    <label class="col-sm-2">
                        상위 카테고리
                    </label>
                    <div class="col-sm-10">
                        <select name="category">
                            {% for categroy in categorys %}
                            <option value="{{ category.pk }}">{{ categroy.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-inline form-group">

                    <label class="col-sm-2">
                        우선순위
                    </label>
                    <div class="col-sm-10">
                        {% if category is None %}
                        <input name="priority" class="form-control" type="text">
                        {% else %}
                        <input name="priority" class="form-control" type="text" value="{{ category.priority }}">
                        {% endif %}
                    </div>
                </div>
                <p>[부모 카테고리가 있을시, 부모카테고리의 우선순위를 따릅니다]</p>

                <input id="submit" type="submit" value="등록"/>
            </fieldset>
        </div>

    </form>
</div>
</div>
{% endblock %}

{% block extrascript %}
{% endblock %}

frontend/templates/super/home.html
{% extends "super/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="home">
    <p>admin 페이지 입니다</p>
    <img src="{% static 'img/admin.png' %}"/>
    <input type="button" value="쇼핑몰로 가기"/>
    <input type="button" value="로그아웃"/>
</div>
{% endblock %}

frontend/templates/super/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href='{% static "css/super/login.css" %}'/>
</head>
<body>
    <div class="login-page">
        <form action="." method="post" >{% csrf_token %}
            <div class="form-conent">
                <div class="form-group">
                    <input type="text" id="user_id" name="user_id" placeholder="ID"/>
                </div>
                <div class="form-group">
                    <input type="text" id="password" name="password" placeholder="Password"/>
                </div>
            </div>
            <input id="btn-login" type="submit" value="login">
        </form>
    </div>
</body>
</html>

frontend/templates/super/member-list.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/table.css" %}
{% endblock %}

{% block content %}
<div id="content">
    <br/>
    <div class="titleArea">
        <h2>member list</h2>
    </div>
    <br/>
    <table class="table">
        <tr>
            <th>No.</th>
            <th>회원 이름</th>
            <th>ID</th>
            <th>Email</th>
            <th>Phone</th>
        </tr>
        {% load custom_tags %}
        {% for member in members|sort_by:'pk' %}
        <tr>
            <td>{{ member.pk }}</td>
            <td>{{ member.username }}</td>
            <td>{{ member.user_id }}</td>
            <td>{{ member.email }}</td>
            <td>{{ member.phone_number }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

frontend/templates/super/order-detail.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/table.css" %}
{% endblock %}

{% block content %}
<h1>order detail</h1>
<div class="cart-list">
    <table>
        <tr>
            <th><label for="id_sender_name">주문자 이름:</label></th>
            <td><p id="id_sender_name">{{ sender_name }}</p></td>
        </tr>
        <tr>
            <th><label for="id_receiver_phone_number">주문자 전화번호:</label></th>
            <td><p id="id_sender_phone_number">{{ sender_phone_number }}</p>
            </td>
        </tr>
        <tr>
            <th><label for="id_receiver_phone_number">주문자 이메일:</label></th>
            <td><p id="id_sender_email">{{ sender_email }}</p></td>
        </tr>
    </table>
    <table>
        <tr>
            <th><label for="id_receiver_name">받는사람:</label></th>
            <td><p id="id_receiver_name">{{ receiver_name }}</td>
        </tr>
        <tr>
            <th><label for="id_receiver_phone_number">받는사람 전화번호:</label></th>
            <td><p id="id_receiver_phone_number">{{ receiver_phone_number }}</p>
            </td>
        </tr>
        <tr>
            <th><label for="id_receiver_address">받는사람 주소:</label></th>
            <td><p id="id_receiver_address">{{ receiver_address }}</p></td>
        </tr>
        <tr>
            <th><label for="id_delivery_message">배송 메시지:</label></th>
            <td><p id="id_delivery_message">{{ delivery_message }}</p></td>
        </tr>
    </table>
    <table>
        <tr>
            <th><label for="id_pay_type">결제방법:</label></th>
            <td><p id="id_pay_type">{{ pay_type }}</p> </td>
        </tr>
        <tr>
            <th><label for="id_status">결제방법:</label></th>
            <td><p id="id_status">{{ status }}</p> </td>
        </tr>
    </table>

    <table>
        <thead>
        <tr>
            <th>상품명</th>
            <th>가격</th>
            <th>수량</th>
            <th>총가격</th>
        </tr>
        </thead>

        <tbody>
        {% load custom_tags %}
        {% for product in order_products %}
        <tr>
            <th>{{ product.product.name}}</th>
            <th>{{ product.product.price}}</th>
            <th>{{ product.amount}}</th>
            <th>{{ product.all_price}}</th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

frontend/templates/super/order-list.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/table.css" %}
{% endblock %}

{% block content %}
<div id="content">
    <br/>
    <div class="titleArea">
        <h2>product list</h2>
    </div>
    <br/>
    <table class="table">
        <tr>
            <th>주문일</th>
            <th>주문 번호</th>
            <th>주문자</th>
            <th>결제 가격</th>
            <th>결제 수단</th>
            <th>주문 상태</th>
        </tr>
        {% load custom_tags %}
        {% for order in orders|unsort_by:'pk' %}
        <tr>
            <td>{{ order.date }}</td>
            <td><a href="{% url 'super:order-detail' order.pk  %}">{{ order.pk }}</a></td>
            <td>{{ order.user.username }}</td>
            <td>{{ order.price }}</td>
            <td>{{ order.pay_type }}</td>
            <td>{{ order.status }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

frontend/templates/super/product-add.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/product-add.css" %}
{% endblock %}
{% block extrafile %}
<script type="text/javascript" src="{% static 'script/jquery.min.js' %}"></script>
{% endblock %}

{% block content %}

<div id="content">
    <br/>
    <div class="titleArea">
        <h2>product add</h2>
    </div>
    <br/>
    <div class="box">
        <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
            <input id="csrf_token" type="hidden" value="{{ csrf_token }}"/>
            <div class="product-add">
                <fieldset>
                    <div class="form-inline form-group">
                        <label class="label col-sm-2">
                            상품 명
                        </label>
                        <div class="col-sm-10">
                            {% if product is None %}
                            <input name="name" class="form-control" type="text">
                            {% else %}
                            <input name="name" class="form-control" type="text" value="{{ product.name }}">
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-inline form-group">
                        <label class="col-sm-2">
                            가격
                        </label>
                        <div class="col-sm-10">
                            {% if product is None %}
                            <input name="price" class="form-control" type="text">
                            {% else %}
                            <input name="price" class="form-control" type="text" value="{{ product.price }}">
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-inline form-group">
                        <label class="col-sm-2">
                            설명
                        </label>
                        <div class="col-sm-10">
                            {% if product is None %}
                            <textarea name="description" class="form-control rounded-0"></textarea>
                            {% else %}
                            <textarea name="description" class="form-control rounded-0"
                                      value="{{ product.description }}"></textarea>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-inline form-group">
                        <label class="col-sm-2">
                            대표 이미지 파일
                        </label>
                        <div class="col-sm-5">
                            {% if product is None %}
                            <input name="img_main" class="form-control" type="file">
                            {% else %}
                            <input name="img_main" class="form-control" type="file" value="{{ product.image_url }}">
                            {% endif %}
                        </div>
                        <div class="col-sm-5">
                            <img class="preview" id="preview_main" src="#"/>
                        </div>
                    </div>

                    <div class="form-inline form-group">
                        <label class="col-sm-2">
                            상세 설명 파일
                        </label>
                        <div class="col-sm-10">
                            {% if product is None %}
                            <input name="img_content" class="form-control" type="file">
                            {% else %}
                            <input name="img_content" class="form-control" type="file" value="{{ product.file_url }}">
                            {% endif %}

                        </div>
                    </div>

                    <div class="form-inline form-group">
                        <label class="col-sm-2">
                            카테고리
                        </label>
                        <div class="col-sm-10">
                            <select class="form-control" name="category" id="category">
                                {% load custom_tags %}
                                {% for category in categorys|sort_by:'pk' %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-inline form-group horizontal-checkbox">
                        <label class="col-sm-2 control-label">
                            재고 유무
                        </label>
                        <div class="col-sm-10">
                            <input type="checkbox" id="is_stock" name="is_stock">
                        </div>
                    </div>

                    <div class="form-inline form-group horizontal-checkbox">
                        <label class="col-sm-2 control-label">
                            메인 전시
                        </label>
                        <div class="col-sm-10">
                            <input type="checkbox" id="is_display" name="is_display">
                        </div>
                    </div>

                    <!--                <div class="form-inline form-group horizontal-checkbox">-->
                    <!--                    <label class="col-sm-2 control-label">-->
                    <!--                        옵션 유무-->
                    <!--                    </label>-->
                    <!--                    <div class="col-sm-10">-->
                    <!--                        <input type="checkbox" id="is_option" name="is_option" class="checkboxChange">-->
                    <!--                    </div>-->
                    <!--                </div>-->

                    <!--                <div class="options">-->
                    <!--                    <div class="plus-icon">-->
                    <!--                        <img id="plus1" src="{% static 'img/plus.png' %}"/>-->
                    <!--                    </div>-->
                    <!--                    <div class="option-border">-->
                    <!--                        <div class="option">-->
                    <!--                            <input type="text" name="option-name" id="option-name" placeholder="옵션 명"/>-->
                    <!--                            <ul>-->
                    <!--                                <li class="plus2-li">+</li>-->
                    <!--                            </ul>-->
                    <!--                        </div>-->
                    <!--                    </div>-->
                    <!--                </div>-->
                    <input id="submit" type="submit" value="등록"/>
                </fieldset>
            </div>

        </form>
    </div>
</div>
{% endblock %}

{% block extrascript %}
{% endblock %}

frontend/templates/super/product-list.html
{% extends "super/base.html" %}
{% block title %}member-list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/super/table.css" %}
{% endblock %}

{% block content %}
<div class="content">
    <br/>
    <div class="titleArea">
        <h2>product list</h2>
    </div>
    <br/>
    <table class="table">
        <tr>
            <th>No.</th>
            <th></th>
            <th>상품 명</th>
            <th>가격</th>
            <th>카테고리</th>
            <th></th>
        </tr>
        {% load custom_tags %}
        {% for product in products|sort_by:'pk' %}
        <tr>
            <td>{{ product.pk }}</td>

            <td>
                <img src="../..{{product.image_url}}"></img>
            </td>
            <td><a href="{% url 'product:detail' product.pk %}">{{ product.name }}</a></td>
            <td>{{ product.price }}</td>
            <td>{{ product.category.name }}</td>
            <!--        <td><a href="{% url 'super:product-update' product.pk %}">수정</a></td>-->
            <td><a href="{% url 'super:product-delete' product.pk %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}