frontend/frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import (handler404, handler500)

from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('super/', include('super.urls'), name='super'),

    path('user/',include('user.urls'), name='user'),
    path('category/<pk>/',CategoryView.as_view(), name='category'),
    path('product/',include('product.urls'), name='product'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 ='frontend.views.page_not_found'
handler500 ='frontend.views.server_error'

frontend/product/urls.py
from django.urls import path

from .views import ProductDV, OrderView, OrderDV

app_name='product'

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order/<pk>', OrderDV.as_view(), name='order_detail'),
    path('<pk>/',ProductDV.as_view(), name='detail'),
]

frontend/user/urls.py
from django.urls import path

from .views import *

app_name='user'

urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('join/', JoinView.as_view(), name='join'),
    path('checkid/<check_id>/', check_id, name='check_id'),
    path('cart/', CartView.as_view(), name='cart'),
    path('order/', OrderView.as_view(), name='order'),
]

frontend/product/forms.py
from django import forms


class OrderForm(forms.Form):
    user = forms.IntegerField(label="주문자")
    sender_name = forms.CharField(label="주문자 명", max_length=100)
    sender_email = forms.EmailField(label='주문자 이메일')
    sender_phone_number = forms.CharField(label='주문자 전화번호', max_length=50)

    receiver_name = forms.CharField(label='받는사람')
    receiver_phone_number = forms.CharField(label='받는사람 전화번호', max_length=50)
    receiver_address = forms.CharField(label='받는사람 주소', max_length=250)
    delivery_message = forms.CharField(label="배송 메시지")

    pay_type = forms.ChoiceField(label='결제방법', choices=[('0', '무통장입금'),
                                                        ('1', '휴대폰소액결제'),
                                                        ('2', '실시간계좌이체'),
                                                        ('3', '신용카드결제'),
                                                        ('4', '카카오페이')])

frontend/user/views.py
import json

import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View, TemplateView, CreateView, FormView
from rest_framework.decorators import api_view
from rest_framework.response import Response

from frontend import default

root_url = default.root_url
api_url = default.api_url
header = default.headers


class Logout(View):
    def get(self, request):
        del request.session['authuser']
        return HttpResponseRedirect(reverse('home'))


class LoginView(View):
    def get(self, request):
        response = requests.get(root_url + api_url + "categorys/")
        if response.status_code is not 200:
            return render(request, 'home.html', dict())

        data = {
            "shop_name": "AWESOME SHOP",
            "categorys": response.json()["data"]
        }
        return render(request, 'user/login.html', data)

    def post(self, request):
        user = {
            'user_id': request.POST['member_id'],
            'password': request.POST['member_password']
        }

        login_response = requests.post(root_url + api_url + "users/login/", headers=header, data=user)

        if login_response.status_code is not 200:
            return HttpResponseRedirect(reverse("user:login"))

        request.session['authuser'] = login_response.json()['data']

        return HttpResponseRedirect(reverse('home'))


class JoinView(View):
    def get(self, request):
        response = requests.get(root_url + api_url + "categorys/")
        if response.status_code is not 200:
            return render(request, 'home.html', dict())

        data = {
            "shop_name": "AWESOME SHOP",
            "categorys": response.json()['data']
        }
        return render(request, 'user/join.html', data)

    def post(selfs, request):
        response = requests.get(root_url + api_url + "categorys/")
        if response.status_code is not 200:
            return render(request, 'home.html', dict())

        data = {
            "shop_name": "AWESOME SHOP",
            "categorys": response.json()['data']
        }
        user = {
            'user_id': request.POST['user_id'],
            'password': request.POST['password'],
            'username': request.POST['username'],
            'email': request.POST['email'],
            'phone_number': request.POST['phone']
        }
        headers = {'Content-Type': 'application/json; charset=utf-8'}
        response = requests.post(root_url + api_url + "users/", headers=headers, data=json.dumps(user))
        if response.status_code is not 201:
            return render(request, 'home.html', data)

        return HttpResponseRedirect(reverse('home'))


class CartView(View):

    def get(self, request):
        default.set_base_data()
        data = default.base_data
        data['carts'] = []
        if 'authuser' in request.session:
            response = requests.get(root_url + api_url + "carts/user/" + str(request.session['authuser']['pk']))
            if response.status_code is not 200:
                return render(request, 'user/cart.html', data)

            data['carts'] = response.json()['data']
        else:
            pass

        return render(request, 'user/cart.html', data)

    def post(self, request):
        default.set_base_data()
        data = default.base_data
        product_amount = request.POST.getlist('amount')
        product_check = request.POST.getlist('checks')
        cart_pk = request.POST.getlist('cart_pk')
        cart_data = []
        for check, cart, amount in zip(product_check, cart_pk, product_amount):
            response = requests.get(root_url + api_url + "products/" + check)
            product = response.json()['data']
            temp_data = {
                'cart_pk':cart,
                'product': product,
                'amount': amount,
                'all_price': int(product['price']) * int(amount)
            }
            cart_data.append(temp_data)
        data["order_products"] = cart_data
        return render(request, 'order.html', data)


class OrderView(View):
    def get(self, request):
        default.set_base_data()
        data = default.base_data
        data[''] = []
        if 'authuser' in request.session:
            response = requests.get(root_url + api_url + "orders/user/" + str(request.session['authuser']['pk']))
            if response.status_code is not 200:
                return render(request, 'user/order.html', data)
            data['orders'] = response.json()['data']
        else:
            pass

        return render(request, 'user/order.html', data)


@api_view(['GET'])
def check_id(request, check_id):
    response = requests.get(root_url + api_url + "users/check/id/" + check_id)
    return Response(response.json())

frontend/templates/user/cart.html
{% extends "base.html" %}
{% block title %}login.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/cart.css" %}
{% endblock %}
{% block content %}

<div id="content">

    <div class="user-box order-box">
        <div class="user-box1">
            <form action="."  method="post">{% csrf_token %}
                <div class="titleArea">
                    <h2>CART</h2>
                </div>
                <hr class="black-hr"/>
                <div class="cart-list">
                    <table border="1">
                        <thead>
                        <tr>
                            <th scope="col">선택</th>
                            <th scope="col">이미지</th>
                            <th scope="col">상품 정보</th>
                            <th scope="col">가격</th>
                            <th scope="col">수량</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% load custom_tags %}
                        {% for cart in carts|unsort_by:'pk' %}
                        <tr>
                            <th><input type="checkbox" name="checks" value="{{ cart.product.pk }}"/></th>
                            <input type="hidden" name="cart_pk" value="{{ cart.pk }}">
                            <td><img style="width:100px; height:auto;" src="{{ cart.product.image_url }}"></td>
                            <td>{{ cart.product.name }}</td>
                            <input type="hidden" name="pk" value="{{ cart.product.pk }}">
                            <td>{{ cart.product.price }}</td>
                            <input type="hidden" name="price" value="{{ cart.product.price }}">
                            <td>{{ cart.amount }}</td>
                            <input type="hidden" name="amount"  value="{{ cart.amount }}">
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <input type="submit" value="구매" class="buy_button2">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block extrascript %}
{% endblock %}

frontend/templates/user/join.html
{% extends "base.html" %}
{% block title %}login.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/join.css" %}
{% endblock %}
{% block content %}

<div id="content">
    <div class="user-box">
        <div class="user-box1">
            <div class="titleArea">
                <h2>JOIN</h2>
            </div>
            <hr class="black-hr"/>
            <form action="." method="post">{% csrf_token %}
                <div class="join-table">
                    <table border="1" summary>
                        <tr>
                            <th scope="row">
                                아이디
                                <img src="{% static 'img/required.gif' %}">
                            </th>
                            <td>
                                <input id="user_id" name="user_id" placeholder="5자리 이상">
                                <span id="idMsg"></span>
                            </td>
                            <td>
                                <input type="button" id="btn-id" value="아이디 체크" class="idcheck_button">
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                비밀번호
                                <img src="{% static 'img/required.gif' %}">
                            </th>
                            <td>
                                <input type="password" id="password" name="password" placeholder="10자리 이상"
                                       autocomplete="new-password">
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">
                                비밀번호 확인
                                <img src="{% static 'img/required.gif' %}">
                            </th>
                            <td>
                                <input type="password" id="password_fonfirm" name="password_fonfirm">
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">
                                이름
                                <img src="{% static 'img/required.gif' %}">
                            </th>
                            <td>
                                <input id="username" name="username">
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">
                                휴대전화
                            </th>
                            <td>
                                <input id="phone" name="phone" placeholder="-없이 숫자만 입력해 주세요.">
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">
                                이메일
                            </th>
                            <td>
                                <input type="email" id="email" name="email">
                            </td>
                            <td></td>
                        </tr>

                    </table>
                </div>
                <input type="submit" value="회원가입" class="join_button"/>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block extrascript %}
{% static "script/user/join.js" %}
{% endblock %}

frontend/templates/user/login.html
{% extends "base.html" %}
{% block title %}login.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/login.css" %}
{% endblock %}
{% block content %}

<div id="content">

    <div class="user-box">

        <div class="user-box1">
            <div class="titleArea">
                <h2>LOGIN</h2>
            </div>
            <hr class="black-hr"/>
            <form action="." method="post">{% csrf_token %}
                <div class="login">
                    <fieldset>
                        <legend>회원로그인</legend>
                        <span class="id01">ID</span>
                        <label class="id ePlaceholder">
                            <input id="member_id" name="member_id" type="text">
                        </label>

                        <span class="id02">PASS</span>
                        <label class="password password ePlaceholder">
                            <input id="member_password" name="member_password" type="password">
                        </label>

                        <input type="submit" value="로그인" class="login_button"/>
                        <input type="submit" value="회원가입" class="login_button"/>
                        <hr>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block extrascript %}
{% endblock %}

frontend/templates/user/order.html
{% extends "base.html" %}
{% block title %}myorder.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/cart.css" %}
{% endblock %}
{% block content %}

<div id="content">

    <div class="user-box order-box">

        <div class="user-box1">
            <div class="titleArea">
                <h2>ORDER</h2>
            </div>
            <hr class="black-hr"/>
            <div class="cart-list">
                <table>
                    <thead>
                    <tr>
                        <th class="img">이미지</th>
                        <th class="name">상품명</th>
                        <th class="etc">가격</th>
                        <th class="etc">수량</th>
                        <th class="etc">총 가격</th>
                    </tr>
                    </thead>
                </table>
                {% load custom_tags %}
                {% for order in orders|unsort_by:'pk' %}
                <table class="order">
                    <a href="{% url 'product:order_detail' order.pk %}"> {{ order.date  }}</a>
                    {% for product in order.order_products %}
                    <tr>
                        <td class="img"><img style="width:100px; height:auto;" src="{{ product.product.image_url }}">
                        </td>
                        <td class="name">{{ product.product.name }}</td>
                        <td class="etc">{{ product.product.price }}</td>
                        <td class="etc">{{ product.amount }}</td>
                        <td class="etc">{{ product.all_price }}</td>
                    </tr>
                    {% endfor %}

                </table>

                <hr class="gray-hr"/>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block extrascript %}
{% endblock %}

frontend/templates/user/order_detail.html
{% extends "base.html" %}
{% block title %}login.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/cart.css" %}
{% endblock %}
{% block content %}

<div id="content">
    <div class="user-box order-box">
        <div class="user-box1">
            <div class="titleArea">
                <h2>ORDER DETAIL</h2>
            </div>
            <hr class="black-hr"/>
            <div class="cart-list">
                <table>
                    <tr>
                        <th><label for="id_date">주문 일:</label></th>
                        <td><p id="id_date">{{ order.date }}</p></td>
                    </tr>                    <tr>
                        <th><label for="id_sender_name">주문자 이름:</label></th>
                        <td><p id="id_sender_name">{{ order.sender_name }}</p></td>
                    </tr>
                    <tr>
                        <th><label for="id_receiver_phone_number">주문자 전화번호:</label></th>
                        <td><p id="id_sender_phone_number">{{ order.sender_phone_number }}</p>
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_receiver_phone_number">주문자 이메일:</label></th>
                        <td><p id="id_sender_email">{{ order.sender_email }}</p></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <th><label for="id_receiver_name">받는사람:</label></th>
                        <td><p id="id_receiver_name">{{ order.receiver_name }}</td>
                    </tr>
                    <tr>
                        <th><label for="id_receiver_phone_number">받는사람 전화번호:</label></th>
                        <td><p id="id_receiver_phone_number">{{ order.receiver_phone_number }}</p>
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_receiver_address">받는사람 주소:</label></th>
                        <td><p id="id_receiver_address">{{ order.receiver_address }}</p></td>
                    </tr>
                    <tr>
                        <th><label for="id_delivery_message">배송 메시지:</label></th>
                        <td><p id="id_delivery_message">{{ order.delivery_message }}</p></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <th><label for="id_pay_type">결제방법:</label></th>
                        <td><p id="id_pay_type">{{ order.pay_type }}</p></td>
                    </tr>
                    <tr>
                        <th><label for="id_status">결제방법:</label></th>
                        <td><p id="id_status">{{ order.status }}</p></td>
                    </tr>
                </table>

                <table>
                    <thead>
                    <tr>
                        <th>상품명</th>
                        <th>가격</th>
                        <th>수량</th>
                        <th>총가격</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% load custom_tags %}
                    {% for product in order.order_products %}
                    <tr>
                        <th>{{ product.product.name}}</th>
                        <th>{{ product.product.price}}</th>
                        <th>{{ product.amount}}</th>
                        <th>{{ product.all_price}}</th>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascript %}
{% endblock %}