frontend/frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import (handler404, handler500)

from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('super/', include('super.urls'), name='super'),

    path('user/',include('user.urls'), name='user'),
    path('category/<pk>/',CategoryView.as_view(), name='category'),
    path('product/',include('product.urls'), name='product'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 ='frontend.views.page_not_found'
handler500 ='frontend.views.server_error'

frontend/product/urls.py
from django.urls import path

from .views import ProductDV, OrderView, OrderDV

app_name='product'

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order/<pk>', OrderDV.as_view(), name='order_detail'),
    path('<pk>/',ProductDV.as_view(), name='detail'),
]

frontend/user/urls.py
from django.urls import path

from .views import *

app_name='user'

urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('join/', JoinView.as_view(), name='join'),
    path('checkid/<check_id>/', check_id, name='check_id'),
    path('cart/', CartView.as_view(), name='cart'),
    path('order/', OrderView.as_view(), name='order'),
]

frontend/product/forms.py
from django import forms


class OrderForm(forms.Form):
    user = forms.IntegerField(label="주문자")
    sender_name = forms.CharField(label="주문자 명", max_length=100)
    sender_email = forms.EmailField(label='주문자 이메일')
    sender_phone_number = forms.CharField(label='주문자 전화번호', max_length=50)

    receiver_name = forms.CharField(label='받는사람')
    receiver_phone_number = forms.CharField(label='받는사람 전화번호', max_length=50)
    receiver_address = forms.CharField(label='받는사람 주소', max_length=250)
    delivery_message = forms.CharField(label="배송 메시지")

    pay_type = forms.ChoiceField(label='결제방법', choices=[('0', '무통장입금'),
                                                        ('1', '휴대폰소액결제'),
                                                        ('2', '실시간계좌이체'),
                                                        ('3', '신용카드결제'),
                                                        ('4', '카카오페이')])

frontend/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% load static %}
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src='{% static "script/jquery.min.js" %}'></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}'/>
    <link rel="stylesheet" type="text/css" href='{% block extrastyle %}{% endblock %}'/>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Patua+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bitter&display=swap" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src='{% block extrascript %}{% endblock %}'></script>

</head>
<body style="background-color: #FFDBE5;">
<div id="wrapper">
    <div class="slide_01" style="left:-485px; display:block;"></div>

    <div id="wrap">
        <div class="logo_top01" id="header">

            <div class="member-bar">
                <ul>
                    {% if request.session.authuser is None %}
                        <li><a href="{% url 'user:login' %}">login</a></li>
                        <li><a href="{% url 'user:join' %}">join</a></li>
                    {% else %}
                        <li><a href="">{{ request.session.authuser.name }}님!</a></li>
                        <li><a href="{% url 'user:logout' %}">logout</a></li>
                    {% endif %}
                    <li><a href="{% url 'user:cart'  %}">cart</a></li>
                    <li><a href="{% url 'user:order'  %}">order</a></li>

                </ul>
            </div>

            <div class="search-bar">
                <fieldset>
                    <input id="keyword" name="keyword" type="text">
                    <img src="{% static 'img/search.gif' %}">
                </fieldset>
            </div>

            <div class="logo_top01-1">
                <h1 class="logo_text"><a href="{% url 'home' %}">{{ shop_name }}</a></h1>
                <div class="nav tabs">
                    {% load custom_tags %}
                    {% if categorys is None %}
                    {% else %}
                        {% for category in categorys|sort_by:'priority' %}
                            {% if category.parent == None %}
                                <div class="nav-item">
                                    <a class="nav-link" href="{% url 'category' category.pk %}">{{ category.name }}</a>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>


        {% block content%}{% endblock %}
<!--        {% block footer %}{% endblock %}-->
    </div>
</div>

<script src='{% static "script/super/product-add.js" %}'>
</script>
</body>
</html>

frontend/templates/base_.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}'/>
    <link rel="stylesheet" type="text/css" href='{% static "css/vuetify.css" %}'/>
    <link rel="stylesheet" type="text/css" href='{% block extrastyle %}{% endblock %}'/>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <script src='{% static "script/vue.js" %}'></script>
    <script src='{% static "script/vuetify.js" %}'></script>
    <script src='{% block extrascript %}{% endblock %}'></script>

</head>
<body>
<div id="wrapper">
    <div class="slide_01" style="left:-485px; display:block;"></div>

    <div id="wrap">
        <div class="logo_top01" id="header">
            <v-app class="logo_top01-1">
                <h1 class="logo_text">awesome shop</h1>

                <div class="tabs">
                    <template>
                    <v-tabs v-model="tab" background-color="#1ecfff" centered>
                        <v-tab
                            v-for="category in categorys"
                            :key="category">
                            {{ category }}
                        </v-tab>
                        <v-tab>아우터</v-tab>
<!--                        <v-tab>상의</v-tab>-->
<!--                        <v-tab>블라우스</v-tab>-->
<!--                        <v-tab>드레스</v-tab>-->
<!--                        <v-tab>바지</v-tab>-->
<!--                        <v-tab>치마</v-tab>-->
<!--                        <v-tab>가방&신발</v-tab>-->
                    </v-tabs>
                    </template>
                </div>
            </v-app>
        </div>


        {% block content%}{% endblock %}
        {% block footer %}{% endblock %}
    </div>
</div>

<script src='{% static "script/base.js" %}'>
</script>
</body>
</html>

frontend/templates/home.html
{% extends "base.html" %}
{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
    {% static "css/home.css" %}
{% endblock %}
{% block content %}
<div id="content">
    <div id="color_main">
        <div id="color_main1">
            <h2>PRODUCT LIST</h2>
            <div class="gallery">
                <ul class="productList column4">
                    {% load custom_tags %}
                    {% for product in products %}
                        <li class="item">
                            <div class="box">
                                <div class="line">
                                    <div class="gallery-item">
                                        <div class="gallery-item-image">
                                            <a href="{% url 'product:detail' product.pk %}">
                                                <img src="{{ product.image_url }}">
                                            </a>
                                        </div>
                                        <div class="gallery-item-description">
                                            <p class="name">
                                                {{ product.name }}
                                            </p>
                                            <p class="price">
                                                {{ product.price }} 원
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>

            </div>

        </div>
    </div>
</div>

{% endblock content%}

{% block extrascript %}
{% static "script/home.js" %}
{% endblock %}

frontend/templates/home_.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@3.x/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">

</head>
<body>

<div id="app">
    <v-app>
        <div>
            <h1>쇼핑몰</h1>
        </div>

        <v-tabs centered>
            <v-tab>아우터</v-tab>
            <v-tab>상의</v-tab>
            <v-tab>하의</v-tab>
        </v-tabs>

        <!-- Sizes your content based upon application components -->
        <v-content>

            <!-- Provides the application the proper gutter -->
            <v-container class="mb-12">
                <v-layout row>
                    <v-flex xs4>
                        <v-sheet
                                :color="color_1"
                                height="100%"
                                tile>
                            <v-layout
                                    align-center
                                    fill-height
                                    justify-center>
                            </v-layout>
                        </v-sheet>
                    </v-flex>
                    <v-flex xs4>

                        <v-carousel v-model="model" @change="change">
                            <v-carousel-item
                                    v-for="(color, i) in colors"
                                    :key="color">
                                <v-sheet
                                        :color="color"
                                        height="100%"
                                        tile>
                                    <v-layout
                                            align-center
                                            fill-height
                                            justify-center>
                                        <div class="display-3">Slide</div>
                                    </v-layout>
                                </v-sheet>
                            </v-carousel-item>
                        </v-carousel>
                    </v-flex>
                    <v-flex xs4>
                        <v-sheet
                                :color="color_2"
                                height="100%"
                                tile>
                            <v-layout
                                    align-center
                                    fill-height
                                    justify-center>
                            </v-layout>
                        </v-sheet>
                    </v-flex>
                </v-layout>
            </v-container>
            <v-container grid-list-md class="mt-10">
                <v-layout wrap>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>
                    <v-flex xs3>
                        <v-card>
                            <v-img src="http://mblogthumb2.phinf.naver.net/20160813_161/h8275818_1471094359995y2Yww_JPEG/1471093945126.jpg?type=w800"></v-img>
                            <v-card-title>상품</v-card-title>
                            <v-card-text>10000원</v-card-text>
                        </v-card>
                    </v-flex>

                </v-layout>
            </v-container>
        </v-content>

        <v-footer app>
            <!-- -->
        </v-footer>
    </v-app>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
<script>
    new Vue({
        el: '#app',
        vuetify: new Vuetify(),
        data() {
            return {
                colors: [
                    'primary',
                    'secondary',
                    'yellow darken-2',
                    'red',
                    'orange',
                ],
                model: 1
            }
        },
        computed: {
            color_1 () {
                if( this.model == 0 ) {
                    return this.colors[this.colors.length-1]
                }
                return this.colors[this.model-1]
            },
            color_2(){
                if (this.model == this.colors.length-1){
                    return this.colors[0]
                }
                return this.colors[this.model+1]
            }
        },
        watch: {
            color_1: function (val) {
                console.log(val);
            }
        },
        methods: {
            change(n) {

            }
        }
    })


</script>
</body>
</html>

frontend/templates/order.html
{% extends "base.html" %}
{% block title %}login.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}
{% static "css/user/cart.css" %}
{% endblock %}
{% block content %}

<div id="content">

    <div class="user-box order-box">

        <div class="user-box1">
            <div class="titleArea">
                <h2>ORDER</h2>
            </div>
            <hr class="black-hr"/>
            <div class="cart-list">
                <form action="{% url 'product:order' %}" method="post">{% csrf_token %}
                    <table>
                        <tr>
                            <th><label for="id_sender_name">주문자 이름:</label></th>
                            <td><input type="text" name="sender_name" required id="id_sender_name"
                                       value="{{ request.session.authuser.username  }}"></td>
                        </tr>
                        <tr>
                            <th><label for="id_receiver_phone_number">주문자 전화번호:</label></th>
                            <td><input type="text" name="sender_phone_number" maxlength="50" required
                                       id="id_sender_phone_number" value="{{ request.session.authuser.phone_number  }}">
                            </td>
                        </tr>
                        <tr>
                            <th><label for="id_receiver_phone_number">주문자 이메일:</label></th>
                            <td><input type="text" name="sender_email" maxlength="50" required
                                       id="id_sender_email" value="{{ request.session.authuser.email  }}"></td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <th><label for="id_receiver_name">받는사람:</label></th>
                            <td><input type="text" name="receiver_name" required id="id_receiver_name"></td>
                        </tr>
                        <tr>
                            <th><label for="id_receiver_phone_number">받는사람 전화번호:</label></th>
                            <td><input type="text" name="receiver_phone_number" maxlength="50" required
                                       id="id_receiver_phone_number"></td>
                        </tr>
                        <tr>
                            <th><label for="id_receiver_address">받는사람 주소:</label></th>
                            <td><input type="text" name="receiver_address" maxlength="250" required
                                       id="id_receiver_address"></td>
                        </tr>
                        <tr>
                            <th><label for="id_delivery_message">배송 메시지:</label></th>
                            <td><input type="text" name="delivery_message" required id="id_delivery_message"></td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <th><label for="id_pay_type">결제방법:</label></th>
                            <td><select name="pay_type" id="id_pay_type">
                                <option value="0">무통장입금</option>
                                <option value="1">휴대폰소액결제</option>
                                <option value="2">실시간계좌이체</option>
                                <option value="3">신용카드결제</option>
                                <option value="4">카카오페이</option>
                            </select>
                            </td>
                        </tr>
                    </table>

                    <table>
                        <thead>
                        <tr>
                            <th>상품명</th>
                            <th>가격</th>
                            <th>수량</th>
                            <th>총가격</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% load custom_tags %}
                        {% for product in order_products %}
                            {% if 'cart' in request.META.HTTP_REFERER %}
                                <input type="hidden" name="cart_pk" value="{{ product.cart_pk }}">
                            {% endif %}
                        <input type="hidden" name="pk" value="{{ product.product.pk }}"/>
                        <input type="hidden" name="amount" value="{{ product.amount }}"/>
                        <tr>
                            <th>{{ product.product.name}}</th>
                            <th>{{ product.product.price}}</th>
                            <th>{{ product.amount}}</th>
                            <th>{{ product.all_price}}</th>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <input type="submit" value="구매" class="buy_button">
                </form>


            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block extrascript %}
{% endblock %}